name: Build Library

on:
  push:
    branches:
      - main

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Lint the code 🕵
        run: yarn nx run typesafe-rpc:lint

      - name: Check the prettiness of the code 💅
        run: yarn prettier:check

      - name: Run unit tests 🧪
        run: yarn nx run typesafe-rpc:test

      - name: Upload coverage to Codecov 📊
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build code 🛠
        run: yarn nx run typesafe-rpc:build
