name: Publish library

on:
  push:
    tags:
      - v*
      - typesafe-ws-v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Determine package to publish 📦
        id: package
        run: |
          if [[ "${{ github.ref_name }}" == typesafe-ws-v* ]]; then
            echo "name=typesafe-ws" >> "$GITHUB_OUTPUT"
          else
            echo "name=typesafe-rpc" >> "$GITHUB_OUTPUT"
          fi

      - name: Lint the code 🕵
        run: bun run lint

      - name: Check the prettiness of the code 💅
        run: bun run prettier:check

      - name: Run unit tests 🧪
        run: bun run test

      - name: Build code 🛠
        run: bun run build

      - name: Publish the library 🚀
        run: |
          dist="dist/libs/${{ steps.package.outputs.name }}"
          readme="libs/${{ steps.package.outputs.name }}/README.md"

          cp LICENCE "$dist"
          if [ -f "$readme" ]; then
            cp "$readme" "$dist"
          else
            cp README.md "$dist"
          fi

          cd "$dist"
          npm publish --tag latest --access public
